const { TravelAPI } = require("../apis/TravelAPI");
const Enum = require("../helpers/Enum");

const testData = [
  {
    locationId: "1382794",
    name: "Homestead Motel",
    latitude: "35.28594",
    longitude: "-120.66591",
    numReviews: "31",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/14/55/26/66/homestead-motel.jpg",
    ranking: "#1 Best Value of 53 places to stay in San Luis Obispo",
    rating: "1.5",
    distance: "0.1638519433606544",
    isClosed: false,
    price: "$68 - $159",
    hotelClass: "1.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "15520764",
    name: "Downtown SLO Inn",
    latitude: "35.286163",
    longitude: "-120.66567",
    numReviews: "104",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/13/66/91/21/two-queen-beds.jpg",
    ranking: "#2 Best Value of 53 places to stay in San Luis Obispo",
    rating: "2.5",
    distance: "0.184362051580726",
    isClosed: false,
    price: "$66 - $114",
    hotelClass: "2.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "249507",
    name: "Heritage Inn B&B",
    latitude: "35.28651",
    longitude: "-120.66571",
    numReviews: "110",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/06/97/19/ac/heritage-inn-b-b.jpg",
    ranking: "#3 Best Value of 53 places to stay in San Luis Obispo",
    rating: "4.5",
    distance: "0.20180926809334224",
    isClosed: false,
    price: "$85 - $200",
    hotelClass: "0.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "1066130",
    name: "Budget Inn SLO Cal Poly",
    latitude: "35.286633",
    longitude: "-120.66513",
    numReviews: "79",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/01/11/ba/56/king-bed.jpg",
    ranking: "#4 Best Value of 53 places to stay in San Luis Obispo",
    rating: "2.0",
    distance: "0.228929729887689",
    isClosed: false,
    price: "$75 - $140",
    hotelClass: "2.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "81727",
    name: "Olive Tree Inn & Suites San Luis Obispo",
    latitude: "35.28695",
    longitude: "-120.66545",
    numReviews: "778",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/12/bf/6b/29/caption.jpg",
    ranking: "#5 Best Value of 53 places to stay in San Luis Obispo",
    rating: "2.5",
    distance: "0.23503467793365507",
    isClosed: false,
    price: "$88 - $164",
    hotelClass: "2.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "17762001",
    name: "Hotel San Luis Obispo",
    latitude: "35.281723",
    longitude: "-120.66323",
    numReviews: "71",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/28/95/be/9e/hotel-slo-exterior.jpg",
    ranking: "#6 Best Value of 53 places to stay in San Luis Obispo",
    rating: "4.5",
    distance: "0.308679049537932",
    isClosed: false,
    price: "$346 - $521",
    hotelClass: "0.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "589368",
    name: "San Luis Inn & Suites",
    latitude: "35.28751",
    longitude: "-120.66375",
    numReviews: "169",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/0e/d2/10/5f/san-luis-inn-suites.jpg",
    ranking: "#7 Best Value of 53 places to stay in San Luis Obispo",
    rating: "3.0",
    distance: "0.32654892923289924",
    isClosed: false,
    price: "$75 - $139",
    hotelClass: "2.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "11642864",
    name: "SLO Brew Lofts",
    latitude: "35.27937",
    longitude: "-120.663994",
    numReviews: "114",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/0d/5e/6e/51/slo-brew-lofts.jpg",
    ranking: "#8 Best Value of 53 places to stay in San Luis Obispo",
    rating: "4.5",
    distance: "0.395053169441649",
    isClosed: false,
    price: "$372 - $586",
    hotelClass: "0.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "20264157",
    name: "Hotel Cerro",
    latitude: "35.27875",
    longitude: "-120.66346",
    numReviews: "28",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/23/d0/86/a1/classic-king.jpg",
    ranking: "#9 Best Value of 53 places to stay in San Luis Obispo",
    rating: "4.0",
    distance: "0.4473354071709363",
    isClosed: false,
    price: "$260 - $430",
    hotelClass: "0.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "74078",
    name: "Garden Street Inn",
    latitude: "35.278473",
    longitude: "-120.66241",
    numReviews: "274",
    address: "San Luis Obispo, San Luis Obispo County, California",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/22/47/9c/b4/concours-d-elegance.jpg",
    ranking: "#10 Best Value of 53 places to stay in San Luis Obispo",
    rating: "4.0",
    distance: "0.497650548419826",
    isClosed: false,
    price: "$191 - $392",
    hotelClass: "3.0",
    subtype: undefined,
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description: "no description found",
  },
  {
    locationId: "582571",
    name: "Novo Restaurant & Lounge",
    latitude: "35.27942",
    longitude: "-120.66446",
    numReviews: "1281",
    address: "726 Higuera St, San Luis Obispo, CA 93401-3513",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/01/62/14/00/worldwide-flavor-creekside.jpg",
    ranking: "#2 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.6087805673292859",
    isClosed: false,
    price: "$20 - $30",
    hotelClass: undefined,
    subtype: "American",
    phone: "+1 805-543-3986",
    website: "http://www.novorestaurant.com/",
    description: `Set against a rich eclectic backdrop, Novo's international flavors are the leading ingredients in an exotic dining experience. Located downtown San Luis Obispo in a historic turn of the century building with spectacular creekside dining. Multi award winning restaurant for food, service and ambiance. Extensive global and local wine and beer selection. Novo easily accommodates large parties either on one of the patios in in their lower level "cellar room". A favorite with both locals and tourists, Novo is a truly a San Luis Obispo experience.`,
  },
  {
    locationId: "339021",
    name: "Big Sky Cafe",
    latitude: "35.278557",
    longitude: "-120.66431",
    numReviews: "959",
    address: "1121 Broad St, San Luis Obispo, CA 93401-3506",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/17/98/20/97/photo1jpg.jpg",
    ranking: "#4 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.6996975334417539",
    isClosed: false,
    price: "$1 - $30",
    hotelClass: undefined,
    subtype: "American",
    phone: "+1 805-545-5401",
    website: "http://www.bigskycafe.com",
    description: "",
  },
  {
    locationId: "449315",
    name: "Goshi",
    latitude: "35.27838",
    longitude: "-120.66671",
    numReviews: "204",
    address: "570 Higuera St, San Luis Obispo, CA 93401-3849",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/08/da/2b/0c/goshi.jpg",
    ranking: "#6 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.6501701135893121",
    isClosed: false,
    price: "no price found",
    hotelClass: undefined,
    subtype: "Japanese",
    phone: "+1 805-543-8942",
    website: "http://www.menuclub.com",
    description: "",
  },
  {
    locationId: "1628972",
    name: "Luna Red",
    latitude: "35.280266",
    longitude: "-120.66353",
    numReviews: "445",
    address: "1023 Chorro St, San Luis Obispo, CA 93401-3222",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/ab/9d/41/cocktails-in-san-luis.jpg",
    ranking: "#7 of 193 Restaurants in San Luis Obispo",
    rating: "4.0",
    distance: "0.582160445559254",
    isClosed: false,
    price: "$10 - $65",
    hotelClass: undefined,
    subtype: "Latin",
    phone: "+1 805-540-5243",
    website: "http://www.lunaredslo.com/",
    description:
      "Located in the heart of downtown SLO next to the historic Mission Plaza, Luna Red is a lively gathering spot that features a globally- inspired menu of handcrafted plates, craft cocktails and an award-winning global wine.",
  },
  {
    locationId: "859944",
    name: "Mama's Meatball",
    latitude: "35.27825",
    longitude: "-120.66691",
    numReviews: "307",
    address: "570 Higuera St Suite 130, San Luis Obispo, CA 93401-3849",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/07/89/92/8e/mama-s-meatball.jpg",
    ranking: "#9 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.6619489051837691",
    isClosed: false,
    price: "$10 - $25",
    hotelClass: undefined,
    subtype: "Italian",
    phone: "+1 805-544-0861",
    website: "https://www.mamasmeatball.com",
    description:
      "There are many Italian Restaurants in San Luis Obispo, but if you're looking for a truly authentic Italian dining experience, then you should consider Mama's Meatball Restaurant. Rated among the best San Luis Obispo restaurants, Mama's Meatball uses the freshest, quality ingredients grown locally to create some of the most outstanding dishes you could find in San Luis Obispo eateries. For your convenience, Mama's Meatball offers dine-in, takeout and delivery service. Mama's Meatball is one of the few restaurants near Mission San Luis Obispo, and a block away from hotels in downtown San Luis Obispo to offer private dining options and banquet accommodations for corporate parties and family celebrations. Click here to request a quote for your next private event.",
  },
  {
    locationId: "2467215",
    name: "Eureka!",
    latitude: "35.27912",
    longitude: "-120.6624",
    numReviews: "201",
    address: "1141 Chorro Street, San Luis Obispo, CA 93401",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/13/fa/ac/91/cowboy-burger.jpg",
    ranking: "#12 of 193 Restaurants in San Luis Obispo",
    rating: "4.0",
    distance: "0.7455121847452042",
    isClosed: false,
    price: "no price found",
    hotelClass: undefined,
    subtype: "American",
    phone: "+1 805-903-1141",
    website: "http://eurekarestaurantgroup.com/blog/locations/san-luis-obispo/",
    description:
      "Eureka! features an elevated collection of all-American fare paired with local craft beers, small-batch whiskeys, and cocktails making it the perfect place for for the local community to dine, drink and socialize.",
  },
  {
    locationId: "10732821",
    name: "Flour House",
    latitude: "35.27891",
    longitude: "-120.664894",
    numReviews: "129",
    address: "690 Higuera St, San Luis Obispo, CA 93401-3511",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/0c/aa/d8/40/img-20160823-wa0004-largejpg.jpg",
    ranking: "#14 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.6409095698531663",
    isClosed: false,
    price: "no price found",
    hotelClass: undefined,
    subtype: "Italian",
    phone: "+1 805-544-5282",
    website: "http://www.flourhouseslo.com/",
    description: "",
  },
  {
    locationId: "6372128",
    name: "La Locanda",
    latitude: "35.278885",
    longitude: "-120.66313",
    numReviews: "104",
    address: "1137 Garden St, San Luis Obispo, CA 93401-3508",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/06/62/01/a3/la-locanda.jpg",
    ranking: "#16 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.724495974124332",
    isClosed: false,
    price: "no price found",
    hotelClass: undefined,
    subtype: "Italian",
    phone: "+1 805-548-1750",
    website: "http://www.lalocandaslo.com",
    description: "",
  },
  {
    locationId: "17469597",
    name: "Mistura Restaurant",
    latitude: "35.278107",
    longitude: "-120.66677",
    numReviews: "64",
    address: "570 Higuera St, San Luis Obispo, CA 93401",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/1a/cb/d0/d9/photo0jpg.jpg",
    ranking: "#21 of 193 Restaurants in San Luis Obispo",
    rating: "4.5",
    distance: "0.6795901776768954",
    isClosed: false,
    price: "$20 - $35",
    hotelClass: undefined,
    subtype: "Peruvian",
    phone: "+1 805-439-3292",
    website:
      "https://www.misturarestaurants.com/?y_source=1_MzQyMTUxNTQtNzY5LWxvY2F0aW9uLndlYnNpdGU%3D",
    description:
      "The word Mistura brings together the essence of Peru, a vision of its people and cuisine, a wondrous blend of cultures of priceless heritage. Our Mistura is a modern Peruvian restaurant that is as lively as the country and biodiversity it celebrates. Mistura captures the multicultural spirit of Peru, combining its native Incan and Pre-Columbian culinary heritage with the Italian, Spanish, Japanese, and Chinese influences that embody the country's flavorful cuisine. Mistura is an authentic tribute to the diversity of Peruvian food, proposing familiar yet unexpected and adventurous flavors.",
  },
  {
    locationId: "820041",
    name: "F.McLintocks Saloon",
    latitude: "35.27882",
    longitude: "-120.66482",
    numReviews: "157",
    address: "686 Higuera St, San Luis Obispo, CA 93401-3511",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/0f/d4/1f/a9/20170709-103041-largejpg.jpg",
    ranking: "#22 of 193 Restaurants in San Luis Obispo",
    rating: "4.0",
    distance: "0.6530582694160058",
    isClosed: false,
    price: "no price found",
    hotelClass: undefined,
    subtype: "American",
    phone: "+1 805-541-0686",
    website: "http://www.mclintocks.com",
    description: "",
  },
  {
    locationId: "273715",
    name: "Farmers Market",
    latitude: "35.278614",
    longitude: "-120.66491",
    numReviews: "354",
    address: "Higuera Street, San Luis Obispo, CA",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/0f/97/65/ef/photo0jpg.jpg",
    ranking: "#3 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.6706437383497544",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Flea & Street Markets",
    phone: "+1 805-824-7383",
    website: "http://www.slocountyfarmers.org/",
    description:
      "Every Thursday night through out the year, the city hosts a delightful outdoor market/festival where local farmers sell the freshest fruits, vegetables and produce while local musicians and performers entertain the crowds.",
  },
  {
    locationId: "128038",
    name: "Mission San Luis Obispo de Tolosa",
    latitude: "35.28063",
    longitude: "-120.66481",
    numReviews: "689",
    address: "751 Palm St, San Luis Obispo, CA 93401-3521",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/0f/40/ec/5f/beautiful-historic-california.jpg",
    ranking: "#7 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.4779905139698471",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Missions",
    phone: "+1 805-781-8220",
    website: "http://www.missionsanluisobispo.org/",
    description:
      "Founded on September 1, 1772, this is considered one of the most beautiful missions in California and still serves as an active church in the community.",
  },
  {
    locationId: "279138",
    name: "Mission Plaza",
    latitude: "35.280464",
    longitude: "-120.66375",
    numReviews: "129",
    address: "San Luis Obispo, CA",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/0a/54/fc/85/the-mission-church.jpg",
    ranking: "#12 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.5523034354282477",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Points of Interest & Landmarks",
    phone: "no phone number found",
    website: "https://www.tripadvisor.com/",
    description:
      "Two-block area of downtown serves as the community's cultural and social center complemented with great shopping, outdoor and indoor dining and nightlife.",
  },
  {
    locationId: "279137",
    name: "San Luis Obispo Children's Museum",
    latitude: "35.278908",
    longitude: "-120.66618",
    numReviews: "89",
    address: "1010 Nipomo St, San Luis Obispo, CA 93401-3870",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/1e/0c/5d/34/museum-clock-tower.jpg",
    ranking: "#13 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.6023168463230919",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Children's Museums",
    phone: "805-544-KIDS",
    website: "http://www.slocm.org",
    description:
      "Three floors of interactive exhibits and engaging spaces designed for kiddos 2-10 years of age and their families.",
  },
  {
    locationId: "279173",
    name: "History Center and Museum of San Luis Obispo County",
    latitude: "35.280144",
    longitude: "-120.66483",
    numReviews: "72",
    address: "696 Monterey St, San Luis Obispo, CA 93401-3515",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/0d/99/44/a7/carnegie-city-library.jpg",
    ranking: "#19 of 69 things to do in San Luis Obispo",
    rating: "4.0",
    distance: "0.5220677716227446",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "History Museums",
    phone: "+1 805-543-0638",
    website: "http://historycenterslo.org",
    description:
      "Located in the former Carnegie Library, this museum traces the history of San Luis Obispo County from the era of the Chumash and Salinan Indians to present day.",
  },
  {
    locationId: "279175",
    name: "San Luis Obispo Repertory Theatre",
    latitude: "35.28246",
    longitude: "-120.66296",
    numReviews: "48",
    address: "888 Morro St, San Luis Obispo, CA 93401-2711",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/10/97/5d/ae/the-foreigner-2015-photo.jpg",
    ranking: "#23 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.4800838447868857",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Theaters",
    phone: "+1 805-786-2440",
    website: "http://www.slorep.org",
    description:
      "Unforgettable Characters. Extraordinary Stories.Live Theatre on the Central Coast since 1947.San Luis Obispo Repertory Theatre is a professional, nonprofit, regional theatre providing year-round entertainment for our community and its visitors.",
  },
  {
    locationId: "4288288",
    name: "Museum of Art",
    latitude: "35.279663",
    longitude: "-120.664856",
    numReviews: "61",
    address: "1010 Broad St, San Luis Obispo, CA 93401-3505",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-f/09/1b/a5/cb/photo0jpg.jpg",
    ranking: "#24 of 69 things to do in San Luis Obispo",
    rating: "4.0",
    distance: "0.5674796909075998",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Specialty Museums",
    phone: "+1 805-543-8562",
    website: "http://www.sloma.org",
    description: "",
  },
  {
    locationId: "8409322",
    name: "Palm Theatre",
    latitude: "35.28145",
    longitude: "-120.66368",
    numReviews: "15",
    address: "817 Palm St, San Luis Obispo, CA 93401-3257",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/18/15/a5/9a/photo5jpg.jpg",
    ranking: "#40 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.4813988085403238",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Theaters",
    phone: "+1 805-541-5161",
    website: "http://www.thepalmtheatre.com/",
    description: "",
  },
  {
    locationId: "6594428",
    name: "San Luis Obispo County Library",
    latitude: "35.28228",
    longitude: "-120.66216",
    numReviews: "21",
    address: "995 Palm St, San Luis Obispo, CA 93401-3218",
    photo:
      "https://media-cdn.tripadvisor.com/media/photo-s/13/9f/de/a8/photo1jpg.jpg",
    ranking: "#34 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.5543055866397065",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Libraries",
    phone: "+1 805-781-5991",
    website: "https://www.tripadvisor.com/",
    description: "",
  },
  {
    locationId: "10136761",
    name: "SLO Skate Park",
    latitude: "35.289143",
    longitude: "-120.665924",
    numReviews: "7",
    address: "1050 Oak St Santa Rosa Park, San Luis Obispo, CA 93405-2358",
    photo:
      "https://www.ncenet.com/wp-content/uploads/2020/04/No-image-found.jpg",
    ranking: "#47 of 69 things to do in San Luis Obispo",
    rating: "4.5",
    distance: "0.5813150978112349",
    isClosed: false,
    price: undefined,
    hotelClass: undefined,
    subtype: "Playgrounds",
    phone: "+1 805-781-7067",
    website:
      "http://www.slocity.org/government/department-directory/parks-and-recreation/slo-skate-park",
    description: "",
  },
];

const getTravelInfo = async (req, res) => {
  // const region = req.query.region;
  // const pre = req.query.pre;

  // const travelApi = new TravelAPI(region);
  // let hotelData = [];
  // let restaurantData = [];
  // let attractionData = [];
  // if (pre.hotels) {
  //   await travelApi.callAPI(Enum.url.HOTEL_URL);
  //   hotelData = travelApi.cleanHotelData();
  // }
  // if (pre.restaurants) {
  //   await travelApi.callAPI(Enum.url.RESTAURANT_URL);
  //   restaurantData = travelApi.cleanRestaurantData();
  // }
  // if (pre.attractions) {
  //   await travelApi.callAPI(Enum.url.ATTRACTION_URL);
  //   attractionData = travelApi.cleanAttractionData();
  // }
  // const resultData = [...hotelData, ...restaurantData, ...attractionData];

  // if (resultData.length == 0) {
  //   res.status(400).json(resultData);
  // } else {
  //   res.status(200).json(resultData);
  // }

  if (testData.length == 0) {
    res.status(400).json(testData);
  } else {
    res.status(200).json(testData);
  }
};

module.exports = {
  getTravelInfo,
};
